apiVersion: batch/v1
kind: Job
metadata:
  generateName: free-service-job
  namespace: free-service
  labels:
    purpose: free-service-label
spec:
  template:
    spec:
      containers:
      - name: free-service-job-container
        image: 905418338938.dkr.ecr.us-east-1.amazonaws.com/mp12-repository:latest
        resources:
          limits:
            cpu: "0.9"  
        env:
        - name: DATASET
          value: "mnist"
        - name: TYPE
          value: "ff"
      restartPolicy: Never
  backoffLimit: 4
